name: Shared setup workflow

inputs:
  subrepo:
    description: "The subrepo to setup"
    required: true

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.13

    - name: setup dependencies
      shell: bash
      run: |
        cd ${{ inputs.subrepo }}
        uv sync --locked --all-extras --dev

    - name: set up path
      shell: bash
      run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
