/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuration/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gen Config File
         * @description Return a fully structured configuration as the response.
         *     The configuration format should be determined by an http header (application/yaml, application/json).
         */
        post: operations["gen_config_file_api_configuration_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opc/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Search Opc */
        get: operations["read_search_opc_api_opc_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verify-connection/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Connection Db */
        post: operations["verify_connection_db_api_verify_connection_db_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verify-connection/opc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Connection Opc */
        post: operations["verify_connection_opc_api_verify_connection_opc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionScheduleConfig */
        ActionScheduleConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "action_schedule";
            /**
             * Delta Action
             * @default false
             */
            delta_action: boolean;
            /** Delta Bounds */
            delta_bounds?: [
                number,
                number
            ][];
            /**
             * N Updates
             * @default 1
             */
            n_updates: number;
            /**
             * Replay Ratio
             * @default 1
             */
            replay_ratio: number;
            /**
             * Update Freq
             * @default 1
             */
            update_freq: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            /** Action Schedule */
            action_schedule?: number[][];
        };
        /** ActivationConfig */
        ActivationConfig: {
            /** Name */
            name: string;
            /** Args */
            args?: unknown[];
            /** Kwargs */
            kwargs?: Record<string, never>;
        };
        /** ActorCriticEvalConfig */
        ActorCriticEvalConfig: {
            /**
             * Name
             * @default actor-critic
             */
            name: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Num Test States
             * @default 30
             */
            num_test_states: number;
            /**
             * Num Uniform Actions
             * @default 100
             */
            num_uniform_actions: number;
            /**
             * Critic Samples
             * @default 5
             */
            critic_samples: number;
        };
        /** AdamConfig */
        AdamConfig: {
            /**
             * Name
             * @default adam
             * @constant
             */
            name: "adam";
            /**
             * Lr
             * @default 0.0001
             */
            lr: number;
            /**
             * Weight Decay
             * @default 0
             */
            weight_decay: number;
        };
        /** AddRawConfig */
        AddRawConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "add_raw";
        };
        /** AffineConfig */
        AffineConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "affine";
            /**
             * Scale
             * @default 1
             */
            scale: number;
            /**
             * Bias
             * @default 0
             */
            bias: number;
        };
        /**
         * Agg
         * @enum {string}
         */
        Agg: "avg" | "last" | "bool_or";
        /** AllTheTimeTCConfig */
        AllTheTimeTCConfig: {
            /**
             * Name
             * @default all-the-time
             */
            name: string;
            /**
             * Min N Step
             * @default 1
             */
            min_n_step: number;
            /**
             * Max N Step
             * @default |???|
             */
            max_n_step: number;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
        };
        /** ArmijoAdamConfig */
        ArmijoAdamConfig: {
            /**
             * Name
             * @default armijo_adam
             * @constant
             */
            name: "armijo_adam";
            /**
             * Lr
             * @default 0.0001
             */
            lr: number;
            /**
             * Weight Decay
             * @default 0
             */
            weight_decay: number;
            /**
             * C
             * @default 0.1
             */
            c: number;
            /**
             * Tau
             * @default 0.5
             */
            tau: number;
            /**
             * Beta
             * @default 0.1
             */
            beta: number;
            /**
             * Max Backtracks
             * @default 10
             */
            max_backtracks: number;
            /**
             * Min Lr
             * @default 0.0001
             */
            min_lr: number;
        };
        /** BaseNNConfig */
        BaseNNConfig: {
            /**
             * Name
             * @default |???|
             */
            name: string;
            base?: components["schemas"]["NNTorsoConfig"];
            /**
             * Head Layer Init
             * @default Xavier
             */
            head_layer_init: string;
            /**
             * Head Activation
             * @default |???|
             */
            head_activation: components["schemas"]["ActivationConfig"][][];
            /**
             * Head Bias
             * @default true
             */
            head_bias: boolean;
        };
        /** BinaryConfig */
        BinaryConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "binary";
            /**
             * Op
             * @default |???|
             * @enum {string}
             */
            op: "prod" | "min" | "max" | "add" | "replace";
            /**
             * Other
             * @default |???|
             */
            other: string;
            /** Other Xform */
            other_xform?: (components["schemas"]["AddRawConfig"] | components["schemas"]["AffineConfig"] | components["schemas"]["BoundsConfig"] | components["schemas"]["DeltaConfig"] | components["schemas"]["GreaterThanConfig"] | components["schemas"]["IdentityConfig"] | components["schemas"]["InverseConfig"] | components["schemas"]["LessThanConfig"] | components["schemas"]["NormalizerConfig"] | components["schemas"]["NullConfig"] | components["schemas"]["PowerConfig"] | components["schemas"]["BinaryConfig"] | components["schemas"]["ScaleConfig"] | components["schemas"]["SplitConfig"] | components["schemas"]["TraceConfig"] | components["schemas"]["ComparatorConfig"])[];
        };
        /** Body_gen_config_file_api_configuration_file_post */
        Body_gen_config_file_api_configuration_file_post: {
            /** File */
            file?: string | null;
        };
        /** BoundsConfig */
        BoundsConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "bounds";
            /**
             * Bounds
             * @default |???|
             */
            bounds: [
                number,
                number
            ];
            /**
             * Mode
             * @default clip
             * @enum {string}
             */
            mode: "clip" | "nan";
        };
        /** ComparatorConfig */
        ComparatorConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "comparator";
            /**
             * Op
             * @default |???|
             * @enum {string}
             */
            op: "<" | ">" | "<=" | ">=" | "==" | "!=";
            /**
             * Val
             * @default 0
             */
            val: number;
        };
        /** CopyImputerConfig */
        CopyImputerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "copy";
            /**
             * Imputation Horizon
             * @default |???|
             */
            imputation_horizon: number;
        };
        /** CountdownConfig */
        CountdownConfig: {
            /**
             * Action Period
             * Format: duration
             * @default |???|
             */
            action_period: string;
            /**
             * Obs Period
             * Format: duration
             * @default |???|
             */
            obs_period: string;
            /**
             * Kind
             * @default no_countdown
             */
            kind: string;
            /**
             * Normalize
             * @default true
             */
            normalize: boolean;
        };
        /** DBConfig */
        DBConfig: {
            /**
             * Drivername
             * @default postgresql+psycopg2
             */
            drivername: string;
            /**
             * Username
             * @default postgres
             */
            username: string;
            /**
             * Password
             * @default password
             */
            password: string;
            /**
             * Ip
             * @default localhost
             */
            ip: string;
            /**
             * Port
             * @default 5432
             */
            port: number;
            /**
             * Db Name
             * @default postgres
             */
            db_name: string;
        };
        /** DB_Status_Request */
        DB_Status_Request: {
            db_config: components["schemas"]["DBConfig"];
            /** Table Name */
            table_name: string;
        };
        /** DB_Status_Response */
        DB_Status_Response: {
            /** Db Status */
            db_status: boolean;
            /** Table Status */
            table_status: boolean;
            /** Has Connected */
            has_connected: boolean;
        };
        /**
         * DataMode
         * @enum {integer}
         */
        DataMode: 1 | 2 | 3;
        /** DeltaConfig */
        DeltaConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "delta";
        };
        /** DepAsyncEnvConfig */
        DepAsyncEnvConfig: {
            /**
             * Name
             * @default dep_async_env
             */
            name: string;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Obs Period
             * Format: duration
             * @default |???|
             */
            obs_period: string;
            /**
             * Update Period
             * Format: duration
             * @default |???|
             */
            update_period: string;
            /**
             * Action Period
             * Format: duration
             * @default |???|
             */
            action_period: string;
            /** Setpoint Ping Period */
            setpoint_ping_period?: string | null;
            /**
             * Opc Conn Url
             * @default |???|
             */
            opc_conn_url: string;
            /**
             * Opc Ns
             * @default |???|
             */
            opc_ns: number;
            /** Client Cert Path */
            client_cert_path?: string | null;
            /** Client Private Key Path */
            client_private_key_path?: string | null;
            /** Server Cert Path */
            server_cert_path?: string | null;
            /** Application Uri */
            application_uri?: string | null;
            db?: components["schemas"]["TagDBConfig"];
            /**
             * Action Tolerance
             * Format: duration
             * @default |???|
             */
            action_tolerance: string;
        };
        /** DepInteractionConfig */
        DepInteractionConfig: {
            /**
             * Obs Period
             * Format: duration
             * @default |???|
             */
            obs_period: string;
            /**
             * Action Period
             * Format: duration
             * @default |???|
             */
            action_period: string;
            /**
             * Update Period
             * Format: duration
             * @default |???|
             */
            update_period: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "dep_interaction";
            /**
             * Historical Batch Size
             * @default 10000
             */
            historical_batch_size: number;
            /** Hist Chunk Start */
            hist_chunk_start?: string | null;
            /**
             * Checkpoint Path
             * Format: path
             * @default outputs/checkpoints
             */
            checkpoint_path: string;
            /**
             * Restore Checkpoint
             * @default true
             */
            restore_checkpoint: boolean;
            heartbeat?: components["schemas"]["HeartbeatConfig"];
            /** Warmup Period */
            warmup_period?: string | null;
        };
        /** EMAFilterConfig */
        EMAFilterConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "exp_moving";
            /**
             * Alpha
             * @default 0.99
             */
            alpha: number;
            /**
             * Tolerance
             * @default 2
             */
            tolerance: number;
            /**
             * Warmup
             * @default 10
             */
            warmup: number;
        };
        /** EnsembleCriticConfig */
        EnsembleCriticConfig: {
            /**
             * Name
             * @default ensemble
             * @constant
             */
            name: "ensemble";
            critic_network?: components["schemas"]["EnsembleCriticNetworkConfig"];
            /** Critic Optimizer */
            critic_optimizer?: components["schemas"]["RmspropConfig"] | components["schemas"]["AdamConfig"] | components["schemas"]["SgdConfig"] | components["schemas"]["ArmijoAdamConfig"] | components["schemas"]["LSOConfig"];
            /** Buffer */
            buffer?: components["schemas"]["UniformReplayBufferConfig"] | components["schemas"]["PriorityReplayBufferConfig"] | components["schemas"]["EnsembleUniformReplayBufferConfig"] | components["schemas"]["MixedHistoryBufferConfig"];
            /**
             * Polyak
             * @default 0.995
             */
            polyak: number;
            /**
             * Target Sync Freq
             * @default 1
             */
            target_sync_freq: number;
            /**
             * Discrete Control
             * @default false
             */
            discrete_control: boolean;
        };
        /** EnsembleCriticNetworkConfig */
        EnsembleCriticNetworkConfig: {
            /**
             * Name
             * @default ensemble
             * @constant
             */
            name: "ensemble";
            /**
             * Ensemble
             * @default 1
             */
            ensemble: number;
            /** Bootstrap Reduct */
            bootstrap_reduct?: components["schemas"]["MinReduct"] | components["schemas"]["MaxReduct"] | components["schemas"]["MeanReduct"] | components["schemas"]["MedianReduct"] | components["schemas"]["PercentileReduct"];
            /** Policy Reduct */
            policy_reduct?: components["schemas"]["MinReduct"] | components["schemas"]["MaxReduct"] | components["schemas"]["MeanReduct"] | components["schemas"]["MedianReduct"] | components["schemas"]["PercentileReduct"];
            /**
             * Vmap
             * @default false
             */
            vmap: boolean;
            base?: components["schemas"]["NNTorsoConfig"];
        };
        /** EnsembleUniformReplayBufferConfig */
        EnsembleUniformReplayBufferConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "ensemble_uniform";
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Memory
             * @default 1000000
             */
            memory: number;
            /**
             * Batch Size
             * @default 256
             */
            batch_size: number;
            /**
             * N Most Recent
             * @default 1
             */
            n_most_recent: number;
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Ensemble
             * @default 1
             */
            ensemble: number;
            /**
             * Data Subset
             * @default 1
             */
            data_subset: number;
        };
        /** EpsilonGreedySarsaConfig */
        EpsilonGreedySarsaConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "epsilon_greedy_sarsa";
            /**
             * Delta Action
             * @default false
             */
            delta_action: boolean;
            /** Delta Bounds */
            delta_bounds?: [
                number,
                number
            ][];
            /**
             * N Updates
             * @default 1
             */
            n_updates: number;
            /**
             * Replay Ratio
             * @default 1
             */
            replay_ratio: number;
            /**
             * Update Freq
             * @default 1
             */
            update_freq: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            /**
             * Ensemble Targets
             * @default false
             */
            ensemble_targets: boolean;
            /**
             * Epsilon
             * @default 0.1
             */
            epsilon: number;
            /**
             * Samples
             * @default 10000
             */
            samples: number;
            critic?: components["schemas"]["EnsembleCriticConfig"];
        };
        /** EvalConfig */
        EvalConfig: {
            actor_critic?: components["schemas"]["ActorCriticEvalConfig"];
            monte_carlo?: components["schemas"]["MonteCarloEvalConfig"];
            raw_data?: components["schemas"]["RawDataEvalConfig"];
            policy_variance?: components["schemas"]["PolicyVarianceConfig"];
            q_online?: components["schemas"]["QOnlineConfig"];
        };
        /** EvalDBConfig */
        EvalDBConfig: {
            /**
             * Drivername
             * @default |???|
             */
            drivername: string;
            /**
             * Username
             * @default |???|
             */
            username: string;
            /**
             * Password
             * @default |???|
             */
            password: string;
            /**
             * Ip
             * @default |???|
             */
            ip: string;
            /**
             * Port
             * @default |???|
             */
            port: number;
            /**
             * Db Name
             * @default |???|
             */
            db_name: string;
            /**
             * Table Name
             * @default evals
             */
            table_name: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "db";
            /**
             * Table Schema
             * @default public
             */
            table_schema: string;
            /**
             * Lo Wm
             * @default 10
             */
            lo_wm: number;
        };
        /** EventBusConfig */
        EventBusConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Cli Connection
             * @default tcp://localhost:5555
             */
            cli_connection: string;
            /**
             * App Connection
             * @default inproc://corerl_app
             */
            app_connection: string;
        };
        /** ExperimentConfig */
        ExperimentConfig: {
            /**
             * Debug
             * @default false
             */
            debug: boolean;
            /**
             * Device
             * @default cpu
             */
            device: string;
            /**
             * Exp Name
             * @default experiment
             */
            exp_name: string;
            /**
             * Gamma
             * @default 0.9
             */
            gamma: number;
            /**
             * Max Steps
             * @default 200
             */
            max_steps: number;
            /**
             * Offline Steps
             * @default 0
             */
            offline_steps: number;
            /** Offline Eval Iters */
            offline_eval_iters?: number[];
            /**
             * Pipeline Batch Duration
             * Format: duration
             * @default P7D
             */
            pipeline_batch_duration: string;
            /**
             * Render
             * @default 0
             */
            render: number;
            /**
             * Param
             * @default
             */
            param: string;
            /**
             * Param From Hash
             * @default false
             */
            param_from_hash: boolean;
            /**
             * Save Path
             * @default output
             */
            save_path: string;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Run Forever
             * @default false
             */
            run_forever: boolean;
        };
        /** FeatureFlags */
        FeatureFlags: {
            /**
             * Delta Actions
             * @default false
             */
            delta_actions: boolean;
        };
        /** GlobalOddityFilterConfig */
        GlobalOddityFilterConfig: {
            /** Default */
            default?: components["schemas"]["EMAFilterConfig"] | components["schemas"]["IdentityFilterConfig"];
        };
        /** GreaterThanConfig */
        GreaterThanConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "greater_than";
            /**
             * Threshold
             * @default 0
             */
            threshold: number;
            /**
             * Equal
             * @default false
             */
            equal: boolean;
        };
        /** GreedyACConfig */
        GreedyACConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "greedy_ac";
            /**
             * Delta Action
             * @default false
             */
            delta_action: boolean;
            /** Delta Bounds */
            delta_bounds?: [
                number,
                number
            ][];
            /**
             * N Updates
             * @default 1
             */
            n_updates: number;
            /**
             * Replay Ratio
             * @default 1
             */
            replay_ratio: number;
            /**
             * Update Freq
             * @default 1
             */
            update_freq: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            critic?: components["schemas"]["EnsembleCriticConfig"];
            actor?: components["schemas"]["NetworkActorConfig"];
            /**
             * N Actor Updates
             * @default 1
             */
            n_actor_updates: number;
            /**
             * N Critic Updates
             * @default 1
             */
            n_critic_updates: number;
            /**
             * Ensemble Targets
             * @default false
             */
            ensemble_targets: boolean;
            /**
             * Num Samples
             * @default 128
             */
            num_samples: number;
            /**
             * Prop Rho Mult
             * @default 2
             */
            prop_rho_mult: number;
            /**
             * Rho
             * @default 0.1
             */
            rho: number;
            /**
             * Share Batch
             * @default true
             */
            share_batch: boolean;
            /**
             * Uniform Sampling Percentage
             * @default 0.8
             */
            uniform_sampling_percentage: number;
            /**
             * Eval Batch
             * @default true
             */
            eval_batch: boolean;
            /**
             * Ingress Loss
             * @default true
             */
            ingress_loss: boolean;
            /**
             * Most Recent Batch Loss
             * @default true
             */
            most_recent_batch_loss: boolean;
        };
        /** GreedyIQLConfig */
        GreedyIQLConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "greedy_iql";
            /**
             * Delta Action
             * @default false
             */
            delta_action: boolean;
            /** Delta Bounds */
            delta_bounds?: [
                number,
                number
            ][];
            /**
             * N Updates
             * @default 1
             */
            n_updates: number;
            /**
             * Replay Ratio
             * @default 1
             */
            replay_ratio: number;
            /**
             * Update Freq
             * @default 1
             */
            update_freq: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            gac?: components["schemas"]["GreedyACConfig"];
            iql?: components["schemas"]["IQLConfig"];
            /**
             * Temp
             * @default 1
             */
            temp: number;
            /**
             * Expectile
             * @default 0.8
             */
            expectile: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default OK
             */
            status: string;
            /**
             * Time
             * @default 2025-01-01T00:00:00+00:00
             */
            time: string;
        };
        /** HeartbeatConfig */
        HeartbeatConfig: {
            /** Heartbeat Node Id */
            heartbeat_node_id?: string | null;
            /**
             * Heartbeat Period
             * Format: duration
             * @default PT5S
             */
            heartbeat_period: string;
            /**
             * Max Counter
             * @default 1000
             */
            max_counter: number;
        };
        /** IQLConfig */
        IQLConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "iql";
            /**
             * Delta Action
             * @default false
             */
            delta_action: boolean;
            /** Delta Bounds */
            delta_bounds?: [
                number,
                number
            ][];
            /**
             * N Updates
             * @default 1
             */
            n_updates: number;
            /**
             * Replay Ratio
             * @default 1
             */
            replay_ratio: number;
            /**
             * Update Freq
             * @default 1
             */
            update_freq: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            critic?: components["schemas"]["EnsembleCriticConfig"];
            actor?: components["schemas"]["NetworkActorConfig"];
            /**
             * N Actor Updates
             * @default 1
             */
            n_actor_updates: number;
            /**
             * N Critic Updates
             * @default 1
             */
            n_critic_updates: number;
            /**
             * Temp
             * @default 1
             */
            temp: number;
            /**
             * Expectile
             * @default 0.8
             */
            expectile: number;
        };
        /** IdentityConfig */
        IdentityConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "identity";
        };
        /** IdentityFilterConfig */
        IdentityFilterConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "identity";
        };
        /** IdentityImputerConfig */
        IdentityImputerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "identity";
        };
        /** InACConfig */
        InACConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "inac";
            /**
             * Delta Action
             * @default false
             */
            delta_action: boolean;
            /** Delta Bounds */
            delta_bounds?: [
                number,
                number
            ][];
            /**
             * N Updates
             * @default 1
             */
            n_updates: number;
            /**
             * Replay Ratio
             * @default 1
             */
            replay_ratio: number;
            /**
             * Update Freq
             * @default 1
             */
            update_freq: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            critic?: components["schemas"]["EnsembleCriticConfig"];
            actor?: components["schemas"]["NetworkActorConfig"];
            /**
             * N Actor Updates
             * @default 1
             */
            n_actor_updates: number;
            /**
             * N Critic Updates
             * @default 1
             */
            n_critic_updates: number;
            /**
             * Ensemble Targets
             * @default false
             */
            ensemble_targets: boolean;
            /**
             * Eps
             * @default 1e-8
             */
            eps: number;
            /**
             * Exp Threshold
             * @default 10000
             */
            exp_threshold: number;
            /**
             * Temp
             * @default 1
             */
            temp: number;
        };
        /** InfraConfig */
        InfraConfig: {
            db?: components["schemas"]["DBConfig"];
        };
        /** InverseConfig */
        InverseConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "inverse";
            /**
             * Tolerance
             * @default 0.0001
             */
            tolerance: number;
        };
        /** LSOConfig */
        LSOConfig: {
            /**
             * Name
             * @default lso
             * @constant
             */
            name: "lso";
            /**
             * Lr
             * @default 0.0001
             */
            lr: number;
            /**
             * Weight Decay
             * @default 0
             */
            weight_decay: number;
            /**
             * Max Backtracking Steps
             * @default 30
             */
            max_backtracking_steps: number;
            /**
             * Unit Norm Direction
             * @default false
             */
            unit_norm_direction: boolean;
            /**
             * Fallback Step Size
             * @default 0.0001
             */
            fallback_step_size: number;
            optim?: components["schemas"]["OptimConfig"];
            init?: components["schemas"]["LSOInitConfig"];
            search_condition?: components["schemas"]["SearchConditionConfig"];
        };
        /** LSOInitConfig */
        LSOInitConfig: {
            /**
             * Name
             * @default To
             */
            name: string;
        };
        /** LessThanConfig */
        LessThanConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "less_than";
            /**
             * Threshold
             * @default 0
             */
            threshold: number;
            /**
             * Equal
             * @default false
             */
            equal: boolean;
        };
        /** LinearImputerConfig */
        LinearImputerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "linear";
            /**
             * Max Gap
             * @default |???|
             */
            max_gap: number;
        };
        /** MainConfig */
        MainConfig: {
            infra?: components["schemas"]["InfraConfig"];
            /** Metrics */
            metrics?: components["schemas"]["MetricsDBConfig"] | components["schemas"]["PandasMetricsConfig"];
            /** Evals */
            evals?: components["schemas"]["EvalDBConfig"];
            event_bus?: components["schemas"]["EventBusConfig"];
            experiment?: components["schemas"]["ExperimentConfig"];
            feature_flags?: components["schemas"]["FeatureFlags"];
            /** Log Path */
            log_path?: string | null;
            /**
             * Env
             * @default |???|
             */
            env: components["schemas"]["SimAsyncEnvConfig"] | components["schemas"]["DepAsyncEnvConfig"];
            /**
             * Interaction
             * @default |???|
             */
            interaction: components["schemas"]["SimInteractionConfig"] | components["schemas"]["DepInteractionConfig"];
            pipeline?: components["schemas"]["PipelineConfig"];
            /** Agent */
            agent?: components["schemas"]["ActionScheduleConfig"] | components["schemas"]["GreedyACConfig"] | components["schemas"]["GreedyIQLConfig"] | components["schemas"]["InACConfig"] | components["schemas"]["IQLConfig"] | components["schemas"]["RandomAgentConfig"] | components["schemas"]["SACConfig"] | components["schemas"]["EpsilonGreedySarsaConfig"] | components["schemas"]["SimpleACConfig"];
            eval_cfgs?: components["schemas"]["EvalConfig"];
            report?: components["schemas"]["ReportConfig"];
        };
        /** MaskedAEConfig */
        MaskedAEConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "masked-ae";
            /**
             * Horizon
             * @default 10
             */
            horizon: number;
            /**
             * Proportion Missing Tolerance
             * @default 0.5
             */
            proportion_missing_tolerance: number;
            /** Trace Values */
            trace_values?: number[];
            /**
             * Buffer Size
             * @default 50000
             */
            buffer_size: number;
            /**
             * Batch Size
             * @default 256
             */
            batch_size: number;
            /**
             * Stepsize
             * @default 0.0001
             */
            stepsize: number;
            /**
             * Err Tolerance
             * @default 0.001
             */
            err_tolerance: number;
            /**
             * Max Update Steps
             * @default 100
             */
            max_update_steps: number;
            /**
             * Training Missing Perc
             * @default 0.25
             */
            training_missing_perc: number;
        };
        /** MaxReduct */
        MaxReduct: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "max";
        };
        /** MeanReduct */
        MeanReduct: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "mean";
        };
        /** MedianReduct */
        MedianReduct: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "median";
        };
        /** MetricsDBConfig */
        MetricsDBConfig: {
            /**
             * Drivername
             * @default |???|
             */
            drivername: string;
            /**
             * Username
             * @default |???|
             */
            username: string;
            /**
             * Password
             * @default |???|
             */
            password: string;
            /**
             * Ip
             * @default |???|
             */
            ip: string;
            /**
             * Port
             * @default |???|
             */
            port: number;
            /**
             * Db Name
             * @default |???|
             */
            db_name: string;
            /**
             * Table Name
             * @default metrics
             */
            table_name: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "db";
            /**
             * Table Schema
             * @default public
             */
            table_schema: string;
            /**
             * Lo Wm
             * @default 1
             */
            lo_wm: number;
        };
        /** MinReduct */
        MinReduct: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "min";
        };
        /** MixedHistoryBufferConfig */
        MixedHistoryBufferConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "mixed_history_buffer";
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            /**
             * Memory
             * @default 1000000
             */
            memory: number;
            /**
             * Batch Size
             * @default 256
             */
            batch_size: number;
            /**
             * N Most Recent
             * @default 1
             */
            n_most_recent: number;
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Online Weight
             * @default 0.75
             */
            online_weight: number;
            /**
             * Ensemble
             * @default 10
             */
            ensemble: number;
            /**
             * Ensemble Probability
             * @default 0.5
             */
            ensemble_probability: number;
        };
        /** MonteCarloEvalConfig */
        MonteCarloEvalConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Precision
             * @default 0.99
             */
            precision: number;
            /**
             * Critic Samples
             * @default 5
             */
            critic_samples: number;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
        };
        /** NNTorsoConfig */
        NNTorsoConfig: {
            /**
             * Name
             * @default fc
             * @constant
             */
            name: "fc";
            /**
             * Bias
             * @default true
             */
            bias: boolean;
            /**
             * Layer Init
             * @default Xavier
             */
            layer_init: string;
            /** Hidden */
            hidden?: number[];
            /** Activation */
            activation?: components["schemas"]["ActivationConfig"][];
        };
        /** NetworkActorConfig */
        NetworkActorConfig: {
            /**
             * Name
             * @default network
             * @constant
             */
            name: "network";
            /**
             * Action Min
             * @default 0
             */
            action_min: number;
            /**
             * Action Max
             * @default 1
             */
            action_max: number;
            actor_network?: components["schemas"]["BaseNNConfig"];
            /** Actor Optimizer */
            actor_optimizer?: components["schemas"]["RmspropConfig"] | components["schemas"]["AdamConfig"] | components["schemas"]["SgdConfig"] | components["schemas"]["ArmijoAdamConfig"] | components["schemas"]["LSOConfig"];
            /** Buffer */
            buffer?: components["schemas"]["UniformReplayBufferConfig"] | components["schemas"]["PriorityReplayBufferConfig"] | components["schemas"]["EnsembleUniformReplayBufferConfig"] | components["schemas"]["MixedHistoryBufferConfig"];
        };
        /** NormalizerConfig */
        NormalizerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "normalize";
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /**
             * From Data
             * @default false
             */
            from_data: boolean;
        };
        /** NullConfig */
        NullConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "null";
        };
        /** OPC_Status_Request */
        OPC_Status_Request: {
            /** Opc Url */
            opc_url: string;
        };
        /** OPC_Status_Response */
        OPC_Status_Response: {
            /** Opc Status */
            opc_status: boolean;
            /** Has Connected */
            has_connected: boolean;
        };
        /** OpcNodeDetail */
        OpcNodeDetail: {
            /** Val */
            val: unknown;
            /** Datatype */
            DataType: string;
            /** Identifier */
            Identifier: string | number;
            /** Nodeid */
            nodeid: string;
            /** Path */
            path: string;
            /** Key */
            key: string;
        };
        /** OpcNodeResponse */
        OpcNodeResponse: {
            /** Nodes */
            nodes: components["schemas"]["OpcNodeDetail"][];
        };
        /** OptimConfig */
        OptimConfig: {
            /**
             * Name
             * @default |???|
             */
            name: string;
            /**
             * Lr
             * @default 0.0001
             */
            lr: number;
            /**
             * Weight Decay
             * @default 0
             */
            weight_decay: number;
        };
        /** PandasMetricsConfig */
        PandasMetricsConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "pandas";
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Output Path
             * @default metric_outputs
             */
            output_path: string;
            /**
             * Buffer Size
             * @default 256
             */
            buffer_size: number;
        };
        /** PerTagImputerConfig */
        PerTagImputerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "per-tag";
            /** Default */
            default?: components["schemas"]["IdentityImputerConfig"] | components["schemas"]["CopyImputerConfig"] | components["schemas"]["LinearImputerConfig"];
        };
        /** PercentileReduct */
        PercentileReduct: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "percentile";
            /**
             * Bootstrap Batch Size
             * @default 10
             */
            bootstrap_batch_size: number;
            /**
             * Bootstrap Samples
             * @default 10
             */
            bootstrap_samples: number;
            /**
             * Percentile
             * @default 0.7
             */
            percentile: number;
        };
        /** PipelineConfig */
        PipelineConfig: {
            /** Tags */
            tags?: components["schemas"]["TagConfig"][];
            /**
             * Max Data Gap
             * Format: duration
             * @default |???|
             */
            max_data_gap: string;
            /** Imputer */
            imputer?: components["schemas"]["PerTagImputerConfig"] | components["schemas"]["MaskedAEConfig"];
            oddity_filter?: components["schemas"]["GlobalOddityFilterConfig"];
            state_constructor?: components["schemas"]["SCConfig"];
            transition_creator?: components["schemas"]["AllTheTimeTCConfig"];
            transition_filter?: components["schemas"]["TransitionFilterConfig"];
        };
        /** PolicyVarianceConfig */
        PolicyVarianceConfig: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * N Samples
             * @default 100
             */
            n_samples: number;
        };
        /** PowerConfig */
        PowerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "power";
            /**
             * Pow
             * @default 1
             */
            pow: number;
        };
        /** PriorityReplayBufferConfig */
        PriorityReplayBufferConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "priority";
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            /**
             * Memory
             * @default 1000000
             */
            memory: number;
            /**
             * Batch Size
             * @default 256
             */
            batch_size: number;
            /**
             * N Most Recent
             * @default 1
             */
            n_most_recent: number;
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Uniform Probability
             * @default 0.01
             */
            uniform_probability: number;
            /**
             * Priority Decay
             * @default 0.99
             */
            priority_decay: number;
        };
        /** QOnlineConfig */
        QOnlineConfig: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** RandomAgentConfig */
        RandomAgentConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "random";
            /**
             * Delta Action
             * @default false
             */
            delta_action: boolean;
            /** Delta Bounds */
            delta_bounds?: [
                number,
                number
            ][];
            /**
             * N Updates
             * @default 1
             */
            n_updates: number;
            /**
             * Replay Ratio
             * @default 1
             */
            replay_ratio: number;
            /**
             * Update Freq
             * @default 1
             */
            update_freq: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
        };
        /** RawDataEvalConfig */
        RawDataEvalConfig: {
            /** Data Modes */
            data_modes?: components["schemas"]["DataMode"][];
            /** Stage Codes */
            stage_codes?: components["schemas"]["StageCode"][];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Tags */
            tags?: string[];
        };
        /** ReportConfig */
        ReportConfig: {
            /**
             * Output Dir
             * Format: path
             * @default outputs/report
             */
            output_dir: string;
            /** Stages */
            stages?: components["schemas"]["StageCode"][];
            /** Tags To Exclude */
            tags_to_exclude?: unknown[];
            /**
             * Stat Table Enabled
             * @default true
             */
            stat_table_enabled: boolean;
            /**
             * Cross Corr Enabled
             * @default true
             */
            cross_corr_enabled: boolean;
            /** Cross Corr Tags */
            cross_corr_tags?: string[] | string[][] | null;
            /**
             * Cross Corr Max Lag
             * @default 100
             */
            cross_corr_max_lag: number;
            /**
             * Hist Enabled
             * @default true
             */
            hist_enabled: boolean;
            /**
             * Hist Show Mean
             * @default true
             */
            hist_show_mean: boolean;
            /** Hist Percentiles */
            hist_percentiles?: number[];
            /**
             * Hist Num Bins
             * @default 30
             */
            hist_num_bins: number;
        };
        /** RmspropConfig */
        RmspropConfig: {
            /**
             * Name
             * @default rms_prop
             * @constant
             */
            name: "rms_prop";
            /**
             * Lr
             * @default 0.0001
             */
            lr: number;
            /**
             * Weight Decay
             * @default 0
             */
            weight_decay: number;
        };
        /** SACConfig */
        SACConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "sac";
            /**
             * Delta Action
             * @default false
             */
            delta_action: boolean;
            /** Delta Bounds */
            delta_bounds?: [
                number,
                number
            ][];
            /**
             * N Updates
             * @default 1
             */
            n_updates: number;
            /**
             * Replay Ratio
             * @default 1
             */
            replay_ratio: number;
            /**
             * Update Freq
             * @default 1
             */
            update_freq: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            critic?: components["schemas"]["EnsembleCriticConfig"];
            actor?: components["schemas"]["NetworkActorConfig"];
            /**
             * N Actor Updates
             * @default 1
             */
            n_actor_updates: number;
            /**
             * N Critic Updates
             * @default 1
             */
            n_critic_updates: number;
            /**
             * Ensemble Targets
             * @default false
             */
            ensemble_targets: boolean;
            /**
             * N Entropy Updates
             * @default 1
             */
            n_entropy_updates: number;
            /**
             * Tau
             * @default -1
             */
            tau: number;
            /**
             * Lr Alpha
             * @default 0.001
             */
            lr_alpha: number;
        };
        /** SCConfig */
        SCConfig: {
            /** Defaults */
            defaults?: (components["schemas"]["AddRawConfig"] | components["schemas"]["AffineConfig"] | components["schemas"]["BoundsConfig"] | components["schemas"]["DeltaConfig"] | components["schemas"]["GreaterThanConfig"] | components["schemas"]["IdentityConfig"] | components["schemas"]["InverseConfig"] | components["schemas"]["LessThanConfig"] | components["schemas"]["NormalizerConfig"] | components["schemas"]["NullConfig"] | components["schemas"]["PowerConfig"] | components["schemas"]["BinaryConfig"] | components["schemas"]["ScaleConfig"] | components["schemas"]["SplitConfig"] | components["schemas"]["TraceConfig"] | components["schemas"]["ComparatorConfig"])[];
            countdown?: components["schemas"]["CountdownConfig"];
        };
        /** ScaleConfig */
        ScaleConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "scale";
            /**
             * Factor
             * @default 1
             */
            factor: number;
        };
        /** SearchConditionConfig */
        SearchConditionConfig: {
            /**
             * Name
             * @default Armijo
             */
            name: string;
            kwargs?: components["schemas"]["SearchConditionKwargsConfig"];
        };
        /** SearchConditionKwargsConfig */
        SearchConditionKwargsConfig: {
            /**
             * C
             * @default 0.1
             */
            c: number;
            /**
             * Beta
             * @default 0.9
             */
            beta: number;
            /**
             * Min Step Size
             * @default 0
             */
            min_step_size: number;
            /**
             * Max Step Size
             * @default 1
             */
            max_step_size: number;
        };
        /** SgdConfig */
        SgdConfig: {
            /**
             * Name
             * @default sgd
             * @constant
             */
            name: "sgd";
            /**
             * Lr
             * @default 0.0001
             */
            lr: number;
            /**
             * Weight Decay
             * @default 0
             */
            weight_decay: number;
        };
        /** SimAsyncEnvConfig */
        SimAsyncEnvConfig: {
            /**
             * Name
             * @default sim_async_env
             */
            name: string;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Obs Period
             * Format: duration
             * @default |???|
             */
            obs_period: string;
            /**
             * Update Period
             * Format: duration
             * @default |???|
             */
            update_period: string;
            /**
             * Action Period
             * Format: duration
             * @default |???|
             */
            action_period: string;
            /** Setpoint Ping Period */
            setpoint_ping_period?: string | null;
            /**
             * Gym Name
             * @default |???|
             */
            gym_name: string;
            /**
             * Init Type
             * @default gym.make
             */
            init_type: ("gym.make" | "custom") | null;
            /** Args */
            args?: unknown[];
            /** Kwargs */
            kwargs?: Record<string, never>;
        };
        /** SimInteractionConfig */
        SimInteractionConfig: {
            /**
             * Obs Period
             * Format: duration
             * @default |???|
             */
            obs_period: string;
            /**
             * Action Period
             * Format: duration
             * @default |???|
             */
            action_period: string;
            /**
             * Update Period
             * Format: duration
             * @default |???|
             */
            update_period: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "sim_interaction";
        };
        /** SimpleACConfig */
        SimpleACConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "simple_ac";
            /**
             * Delta Action
             * @default false
             */
            delta_action: boolean;
            /** Delta Bounds */
            delta_bounds?: [
                number,
                number
            ][];
            /**
             * N Updates
             * @default 1
             */
            n_updates: number;
            /**
             * Replay Ratio
             * @default 1
             */
            replay_ratio: number;
            /**
             * Update Freq
             * @default 1
             */
            update_freq: number;
            /**
             * Discrete Control
             * @default |???|
             */
            discrete_control: boolean;
            /**
             * Gamma
             * @default |???|
             */
            gamma: number;
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            critic?: components["schemas"]["EnsembleCriticConfig"];
            actor?: components["schemas"]["NetworkActorConfig"];
            /**
             * N Actor Updates
             * @default 1
             */
            n_actor_updates: number;
            /**
             * N Critic Updates
             * @default 1
             */
            n_critic_updates: number;
            /**
             * Ensemble Targets
             * @default false
             */
            ensemble_targets: boolean;
            /**
             * Tau
             * @default 0
             */
            tau: number;
        };
        /** SplitConfig */
        SplitConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "split";
            /** Left */
            left?: (components["schemas"]["AddRawConfig"] | components["schemas"]["AffineConfig"] | components["schemas"]["BoundsConfig"] | components["schemas"]["DeltaConfig"] | components["schemas"]["GreaterThanConfig"] | components["schemas"]["IdentityConfig"] | components["schemas"]["InverseConfig"] | components["schemas"]["LessThanConfig"] | components["schemas"]["NormalizerConfig"] | components["schemas"]["NullConfig"] | components["schemas"]["PowerConfig"] | components["schemas"]["BinaryConfig"] | components["schemas"]["ScaleConfig"] | components["schemas"]["SplitConfig"] | components["schemas"]["TraceConfig"] | components["schemas"]["ComparatorConfig"])[];
            /** Right */
            right?: (components["schemas"]["AddRawConfig"] | components["schemas"]["AffineConfig"] | components["schemas"]["BoundsConfig"] | components["schemas"]["DeltaConfig"] | components["schemas"]["GreaterThanConfig"] | components["schemas"]["IdentityConfig"] | components["schemas"]["InverseConfig"] | components["schemas"]["LessThanConfig"] | components["schemas"]["NormalizerConfig"] | components["schemas"]["NullConfig"] | components["schemas"]["PowerConfig"] | components["schemas"]["BinaryConfig"] | components["schemas"]["ScaleConfig"] | components["schemas"]["SplitConfig"] | components["schemas"]["TraceConfig"] | components["schemas"]["ComparatorConfig"])[];
            /** Passthrough */
            passthrough?: boolean | null;
        };
        /**
         * StageCode
         * @enum {integer}
         */
        StageCode: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;
        /**
         * TagConfig
         * @description This is the configuration for our OPC tags. A tag is roughly equivalent to a variable that is sent and received
         *     through an OPC server. It is typically a single primative datatype (e.g. float).
         *
         *     From `PR#335 Discussion <https://github.com/rlcoretech/core-rl/pull/335#discussion_r1898067439>`_ a tag *may*
         *     simultaneously represent both an observation, a reward, and possibly also an action.
         */
        TagConfig: {
            /**
             * Name
             * @default |???|
             */
            name: string;
            /** @default avg */
            agg: components["schemas"]["Agg"];
            /** Node Identifier */
            node_identifier?: string | number | null;
            /**
             * Is Meta
             * @default false
             */
            is_meta: boolean;
            /**
             * Is Endogenous
             * @default true
             */
            is_endogenous: boolean;
            /** Operating Range */
            operating_range?: [
                number | null,
                number | null
            ] | null;
            /** Red Bounds */
            red_bounds?: [
                number | null,
                number | null
            ] | null;
            /** Yellow Bounds */
            yellow_bounds?: [
                number | null,
                number | null
            ] | null;
            /** Change Bounds */
            change_bounds?: [
                number,
                number
            ] | null;
            /** Outlier */
            outlier?: components["schemas"]["EMAFilterConfig"] | components["schemas"]["IdentityFilterConfig"];
            /** Imputer */
            imputer?: (components["schemas"]["IdentityImputerConfig"] | components["schemas"]["CopyImputerConfig"] | components["schemas"]["LinearImputerConfig"]) | null;
            /** Preprocess */
            preprocess?: (components["schemas"]["AddRawConfig"] | components["schemas"]["AffineConfig"] | components["schemas"]["BoundsConfig"] | components["schemas"]["DeltaConfig"] | components["schemas"]["GreaterThanConfig"] | components["schemas"]["IdentityConfig"] | components["schemas"]["InverseConfig"] | components["schemas"]["LessThanConfig"] | components["schemas"]["NormalizerConfig"] | components["schemas"]["NullConfig"] | components["schemas"]["PowerConfig"] | components["schemas"]["BinaryConfig"] | components["schemas"]["ScaleConfig"] | components["schemas"]["SplitConfig"] | components["schemas"]["TraceConfig"] | components["schemas"]["ComparatorConfig"])[];
            /** Reward Constructor */
            reward_constructor?: (components["schemas"]["AddRawConfig"] | components["schemas"]["AffineConfig"] | components["schemas"]["BoundsConfig"] | components["schemas"]["DeltaConfig"] | components["schemas"]["GreaterThanConfig"] | components["schemas"]["IdentityConfig"] | components["schemas"]["InverseConfig"] | components["schemas"]["LessThanConfig"] | components["schemas"]["NormalizerConfig"] | components["schemas"]["NullConfig"] | components["schemas"]["PowerConfig"] | components["schemas"]["BinaryConfig"] | components["schemas"]["ScaleConfig"] | components["schemas"]["SplitConfig"] | components["schemas"]["TraceConfig"] | components["schemas"]["ComparatorConfig"])[];
            /** Action Constructor */
            action_constructor?: (components["schemas"]["AddRawConfig"] | components["schemas"]["AffineConfig"] | components["schemas"]["BoundsConfig"] | components["schemas"]["DeltaConfig"] | components["schemas"]["GreaterThanConfig"] | components["schemas"]["IdentityConfig"] | components["schemas"]["InverseConfig"] | components["schemas"]["LessThanConfig"] | components["schemas"]["NormalizerConfig"] | components["schemas"]["NullConfig"] | components["schemas"]["PowerConfig"] | components["schemas"]["BinaryConfig"] | components["schemas"]["ScaleConfig"] | components["schemas"]["SplitConfig"] | components["schemas"]["TraceConfig"] | components["schemas"]["ComparatorConfig"])[] | null;
            /** State Constructor */
            state_constructor?: (components["schemas"]["AddRawConfig"] | components["schemas"]["AffineConfig"] | components["schemas"]["BoundsConfig"] | components["schemas"]["DeltaConfig"] | components["schemas"]["GreaterThanConfig"] | components["schemas"]["IdentityConfig"] | components["schemas"]["InverseConfig"] | components["schemas"]["LessThanConfig"] | components["schemas"]["NormalizerConfig"] | components["schemas"]["NullConfig"] | components["schemas"]["PowerConfig"] | components["schemas"]["BinaryConfig"] | components["schemas"]["ScaleConfig"] | components["schemas"]["SplitConfig"] | components["schemas"]["TraceConfig"] | components["schemas"]["ComparatorConfig"])[] | null;
            /** Filter */
            filter?: (components["schemas"]["AddRawConfig"] | components["schemas"]["AffineConfig"] | components["schemas"]["BoundsConfig"] | components["schemas"]["DeltaConfig"] | components["schemas"]["GreaterThanConfig"] | components["schemas"]["IdentityConfig"] | components["schemas"]["InverseConfig"] | components["schemas"]["LessThanConfig"] | components["schemas"]["NormalizerConfig"] | components["schemas"]["NullConfig"] | components["schemas"]["PowerConfig"] | components["schemas"]["BinaryConfig"] | components["schemas"]["ScaleConfig"] | components["schemas"]["SplitConfig"] | components["schemas"]["TraceConfig"] | components["schemas"]["ComparatorConfig"])[] | null;
        };
        /** TagDBConfig */
        TagDBConfig: {
            /**
             * Drivername
             * @default |???|
             */
            drivername: string;
            /**
             * Username
             * @default |???|
             */
            username: string;
            /**
             * Password
             * @default |???|
             */
            password: string;
            /**
             * Ip
             * @default |???|
             */
            ip: string;
            /**
             * Port
             * @default |???|
             */
            port: number;
            /**
             * Db Name
             * @default |???|
             */
            db_name: string;
            /**
             * Table Name
             * @default sensors
             */
            table_name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Table Schema
             * @default public
             */
            table_schema: string;
            /** @default avg */
            data_agg: components["schemas"]["Agg"];
        };
        /** TraceConfig */
        TraceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "multi_trace";
            /** Trace Values */
            trace_values?: number[];
        };
        /** TransitionFilterConfig */
        TransitionFilterConfig: {
            /** Filters */
            filters?: components["schemas"]["TransitionFilterType"][];
        };
        TransitionFilterType: "only_dp" | "only_no_action_change" | "only_post_dp" | "no_nan" | "only_pre_dp_or_ac";
        /** UniformReplayBufferConfig */
        UniformReplayBufferConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            name: "uniform";
            /**
             * Seed
             * @default |???|
             */
            seed: number;
            /**
             * Memory
             * @default 1000000
             */
            memory: number;
            /**
             * Batch Size
             * @default 256
             */
            batch_size: number;
            /**
             * N Most Recent
             * @default 1
             */
            n_most_recent: number;
            /**
             * Id
             * @default
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    gen_config_file_api_configuration_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_gen_config_file_api_configuration_file_post"];
                "application/json": components["schemas"]["MainConfig"];
                "application/yaml": components["schemas"]["MainConfig"];
                "application/x-yaml": components["schemas"]["MainConfig"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MainConfig"];
                    "application/yaml": components["schemas"]["MainConfig"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    read_search_opc_api_opc_nodes_get: {
        parameters: {
            query: {
                opc_url: string;
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpcNodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_connection_db_api_verify_connection_db_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DB_Status_Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DB_Status_Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_connection_opc_api_verify_connection_opc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OPC_Status_Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OPC_Status_Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
