/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SetupImport } from './routes/setup'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as SetupIndexImport } from './routes/setup/index'
import { Route as SetupStubrequiredImport } from './routes/setup/stub_required'
import { Route as SetupOpctagsconfigImport } from './routes/setup/opc_tags_config'
import { Route as SetupGeneralconfigImport } from './routes/setup/general_config'
import { Route as SetupFinishImport } from './routes/setup/finish'

// Create/Update Routes

const SetupRoute = SetupImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SetupIndexRoute = SetupIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)

const SetupStubrequiredRoute = SetupStubrequiredImport.update({
  id: '/stub_required',
  path: '/stub_required',
  getParentRoute: () => SetupRoute,
} as any)

const SetupOpctagsconfigRoute = SetupOpctagsconfigImport.update({
  id: '/opc_tags_config',
  path: '/opc_tags_config',
  getParentRoute: () => SetupRoute,
} as any)

const SetupGeneralconfigRoute = SetupGeneralconfigImport.update({
  id: '/general_config',
  path: '/general_config',
  getParentRoute: () => SetupRoute,
} as any)

const SetupFinishRoute = SetupFinishImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => SetupRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupImport
      parentRoute: typeof rootRoute
    }
    '/setup/finish': {
      id: '/setup/finish'
      path: '/finish'
      fullPath: '/setup/finish'
      preLoaderRoute: typeof SetupFinishImport
      parentRoute: typeof SetupImport
    }
    '/setup/general_config': {
      id: '/setup/general_config'
      path: '/general_config'
      fullPath: '/setup/general_config'
      preLoaderRoute: typeof SetupGeneralconfigImport
      parentRoute: typeof SetupImport
    }
    '/setup/opc_tags_config': {
      id: '/setup/opc_tags_config'
      path: '/opc_tags_config'
      fullPath: '/setup/opc_tags_config'
      preLoaderRoute: typeof SetupOpctagsconfigImport
      parentRoute: typeof SetupImport
    }
    '/setup/stub_required': {
      id: '/setup/stub_required'
      path: '/stub_required'
      fullPath: '/setup/stub_required'
      preLoaderRoute: typeof SetupStubrequiredImport
      parentRoute: typeof SetupImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexImport
      parentRoute: typeof SetupImport
    }
  }
}

// Create and export the route tree

interface SetupRouteChildren {
  SetupFinishRoute: typeof SetupFinishRoute
  SetupGeneralconfigRoute: typeof SetupGeneralconfigRoute
  SetupOpctagsconfigRoute: typeof SetupOpctagsconfigRoute
  SetupStubrequiredRoute: typeof SetupStubrequiredRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupFinishRoute: SetupFinishRoute,
  SetupGeneralconfigRoute: SetupGeneralconfigRoute,
  SetupOpctagsconfigRoute: SetupOpctagsconfigRoute,
  SetupStubrequiredRoute: SetupStubrequiredRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/setup': typeof SetupRouteWithChildren
  '/setup/finish': typeof SetupFinishRoute
  '/setup/general_config': typeof SetupGeneralconfigRoute
  '/setup/opc_tags_config': typeof SetupOpctagsconfigRoute
  '/setup/stub_required': typeof SetupStubrequiredRoute
  '/setup/': typeof SetupIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/setup/finish': typeof SetupFinishRoute
  '/setup/general_config': typeof SetupGeneralconfigRoute
  '/setup/opc_tags_config': typeof SetupOpctagsconfigRoute
  '/setup/stub_required': typeof SetupStubrequiredRoute
  '/setup': typeof SetupIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/setup': typeof SetupRouteWithChildren
  '/setup/finish': typeof SetupFinishRoute
  '/setup/general_config': typeof SetupGeneralconfigRoute
  '/setup/opc_tags_config': typeof SetupOpctagsconfigRoute
  '/setup/stub_required': typeof SetupStubrequiredRoute
  '/setup/': typeof SetupIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/setup'
    | '/setup/finish'
    | '/setup/general_config'
    | '/setup/opc_tags_config'
    | '/setup/stub_required'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/setup/finish'
    | '/setup/general_config'
    | '/setup/opc_tags_config'
    | '/setup/stub_required'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/setup'
    | '/setup/finish'
    | '/setup/general_config'
    | '/setup/opc_tags_config'
    | '/setup/stub_required'
    | '/setup/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SetupRoute: typeof SetupRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SetupRoute: SetupRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/setup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/setup": {
      "filePath": "setup.tsx",
      "children": [
        "/setup/finish",
        "/setup/general_config",
        "/setup/opc_tags_config",
        "/setup/stub_required",
        "/setup/"
      ]
    },
    "/setup/finish": {
      "filePath": "setup/finish.tsx",
      "parent": "/setup"
    },
    "/setup/general_config": {
      "filePath": "setup/general_config.tsx",
      "parent": "/setup"
    },
    "/setup/opc_tags_config": {
      "filePath": "setup/opc_tags_config.tsx",
      "parent": "/setup"
    },
    "/setup/stub_required": {
      "filePath": "setup/stub_required.tsx",
      "parent": "/setup"
    },
    "/setup/": {
      "filePath": "setup/index.tsx",
      "parent": "/setup"
    }
  }
}
ROUTE_MANIFEST_END */
