services:
  timescale-db:
    # image: timescale/timescaledb:latest-pg16
    image: timescale/timescaledb:2.17.2-pg16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - timescale-storage:/var/lib/postgresql/data

  opc-server:
    build: ./e2e/opc_server
    ports:
      - 4840:4840
    depends_on:
      timescale-db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./e2e/opc_server

  telegraf:
    # image: telegraf:latest
    image: telegraf:1.32.3
    depends_on:
      timescale-db:
        condition: service_healthy
      opc-server:
        condition: service_started
    volumes:
      - ./e2e/telegraf/generated_telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./e2e/telegraf/generated_telegraf.conf
          target: /etc/telegraf/telegraf.conf

  corerl-web:
    # corerl web server for direct main config API
    build:
      context: .
    ports:
      - 8000:8000
    entrypoint: ["python", "/usr/local/bin/corerl_start_web"]
    develop:
      watch:
        - action: rebuild
          path: ./corerl

  coreio:
    # thin client: https://github.com/rlcoretech/coreio

    # By default, use the latest stable image pushed to github container registry.
    image: ghcr.io/rlcoretech/coreio:latest
    pull_policy: always

    # When working with coreio local image, comment out the "image:" line above and
    # uncomment "build:" and "context:" lines below. Assumes that coreio exists within the same directory as core-rl.
    # build:
    #   context: ../coreio/

    depends_on:
      opc-server:
        condition: service_started
      # soft dependency for MainConfig API proxy, thin client can function without this
      # corerl-web:
      #   condition: service_started
    ports:
      - 2222:2222
    volumes:
      - type: volume
        source: thinclient-storage
        target: /app/data

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    depends_on:
      timescale-db:
        condition: service_healthy
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./e2e/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./e2e/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./e2e/grafana/grafana_config_continuous_mountain_car.json:/var/lib/grafana/dashboards/grafana_config_continuous_mountain_car.json

  opc-sim:
    build: 
      context: .
    depends_on:
      timescale-db:
        condition: service_healthy
      opc-server:
        condition: service_started
      telegraf:
        condition: service_started
    volumes:
      - ./e2e/opc_clients:/app/e2e/opc_clients
      - ./config/opc_sim:/app/config/opc_sim
    entrypoint: ["python"]
    develop:
      watch:
        - action: rebuild
          path: ./e2e/opc_clients
    command: [
      "e2e/opc_clients/opc_sim.py", 
      "--config-name", 
      "config/opc_sim/async_mountain_car_continuous.yaml", 
      "opc_endpoint opc.tcp://admin@opc-server:4840/rlcore/server/"
      ]

  config-test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      timescale-db:
        condition: service_healthy
      opc-server:
        condition: service_started
      telegraf:
        condition: service_started
      coreio:
        condition: service_started
      opc-sim:
        condition: service_started
    volumes:
      - ./config:/app/config
      - ./corerl:/app/corerl
    entrypoint: ["python"]
    command: [
      "-m", "corerl.main",
      "--config-name", "dep_mountain_car_continuous",
      "experiment.max_steps=25",
      "env.db.ip=timescale-db",
      "metrics.ip=timescale-db",
      "env.coreio_origin=http://coreio:2222"
    ]

volumes:
  timescale-storage: {}
  grafana-storage: {}
  thinclient-storage: {}
