defaults:
- null
experiment:
  exp_name: OPC_MountainCarContinuous
  param_from_hash: true
  seed: 1
  gamma: 0.99
  run_forever: true
interaction:
  name: dep_interaction
  historical_batch_size: 0
event_bus:
  enabled: false
env:
  name: opc_tsdb_sim_async_env
  obs_period: 00:00:01
  update_period: 00:00:01
  action_period: 00:00:01
  gym_name: MountainCarContinuous-v0
  discrete_control: false
  seed: 1
  db: ${pipeline.db}
  opc_conn_url: opc.tcp://admin@0.0.0.0:4840/rlcore/server/
  opc_ns: 2
  action_tolerance: 00:00:01
agent:
  name: greedy_ac
  n_critic_updates: 1
  n_actor_updates: 1
  n_sampler_updates: 1
  num_samples: 32
  uniform_sampling_percentage: 0.8
  discrete_control: ${env.discrete_control}
  seed: ${experiment.seed}
  critic:
    buffer:
      seed: ${experiment.seed}
  actor:
    buffer:
      seed: ${experiment.seed}
    actor_optimizer:
      lr: 1.0e-05
metrics:
  name: db
  drivername: postgresql+psycopg2
  username: postgres
  password: password
  ip: localhost
  port: 5432
  db_name: postgres
  table_schema: public
  table_name: metrics
  enabled: true
pipeline:
  db:
    drivername: postgresql+psycopg2
    username: postgres
    password: password
    ip: localhost
    port: 5432
    db_name: postgres
    table_schema: public
    table_name: opcua
  state_constructor:
    defaults: []
  transition_creator:
    name: anytime
  tags:
  - name: gym_reward
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: 'null'
    state_constructor:
    - name: 'null'
    is_meta: true
  - name: terminated
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: greater_than
      threshold: 0.5
    - name: scale
      factor: 100.0
    state_constructor: null
    is_meta: true
  - name: truncated
    outlier:
      name: identity
    imputer:
      name: identity
    is_meta: true
  - name: action_0
    operating_range:
    - -1
    - 1
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: power
      pow: 2
    - name: scale
      factor: -0.1
    state_constructor: null
    action_constructor:
    - name: identity
    is_meta: false
  - name: observation_0
    operating_range:
    - -1.2
    - 0.6
    outlier:
      name: identity
    imputer:
      name: identity
  - name: observation_1
    operating_range:
    - -0.07
    - 0.07
    outlier:
      name: identity
    imputer:
      name: identity
