{
 "title": "Dashboard",
 "tags": [
  "rl",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "experiment",
    "query": "SELECT DISTINCT id FROM reward ORDER BY id"
   }
  ]
 },
 "panels": [
  {
   "title": "Action-0",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT frame as time, measurement as value \nFROM action_0 \nWHERE id = ${experiment:raw}\nORDER BY frame",
     "rawQueryText": "SELECT frame as time, measurement as value \nFROM action_0 \nWHERE id = ${experiment:raw}\nORDER BY frame",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Critic Loss",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT frame as time, measurement as value \nFROM critic_loss \nWHERE id = ${experiment:raw}\nORDER BY frame",
     "rawQueryText": "SELECT frame as time, measurement as value \nFROM critic_loss \nWHERE id = ${experiment:raw}\nORDER BY frame",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Reward",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT frame as time, measurement as value \nFROM reward \nWHERE id = ${experiment:raw}\nORDER BY frame",
     "rawQueryText": "SELECT frame as time, measurement as value \nFROM reward \nWHERE id = ${experiment:raw}\nORDER BY frame",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}