/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as RewardRouteImport } from './routes/reward'
import { Route as OpcNavigationRouteImport } from './routes/opc-navigation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsConfigNameRouteImport } from './routes/agents/$config-name'
import { Route as AgentsConfigNameIndexRouteImport } from './routes/agents/$config-name/index'
import { Route as AgentsConfigNameMonitorRouteImport } from './routes/agents/$config-name/monitor'
import { Route as AgentsConfigNameGeneralSettingsRouteImport } from './routes/agents/$config-name/general-settings'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardRoute = RewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const OpcNavigationRoute = OpcNavigationRouteImport.update({
  id: '/opc-navigation',
  path: '/opc-navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsConfigNameRoute = AgentsConfigNameRouteImport.update({
  id: '/agents/$config-name',
  path: '/agents/$config-name',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsConfigNameIndexRoute = AgentsConfigNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsConfigNameRoute,
} as any)
const AgentsConfigNameMonitorRoute = AgentsConfigNameMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AgentsConfigNameRoute,
} as any)
const AgentsConfigNameGeneralSettingsRoute =
  AgentsConfigNameGeneralSettingsRouteImport.update({
    id: '/general-settings',
    path: '/general-settings',
    getParentRoute: () => AgentsConfigNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/opc-navigation': typeof OpcNavigationRoute
  '/reward': typeof RewardRoute
  '/tags': typeof TagsRoute
  '/agents/$config-name': typeof AgentsConfigNameRouteWithChildren
  '/agents': typeof AgentsIndexRoute
  '/agents/$config-name/general-settings': typeof AgentsConfigNameGeneralSettingsRoute
  '/agents/$config-name/monitor': typeof AgentsConfigNameMonitorRoute
  '/agents/$config-name/': typeof AgentsConfigNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/opc-navigation': typeof OpcNavigationRoute
  '/reward': typeof RewardRoute
  '/tags': typeof TagsRoute
  '/agents': typeof AgentsIndexRoute
  '/agents/$config-name/general-settings': typeof AgentsConfigNameGeneralSettingsRoute
  '/agents/$config-name/monitor': typeof AgentsConfigNameMonitorRoute
  '/agents/$config-name': typeof AgentsConfigNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/opc-navigation': typeof OpcNavigationRoute
  '/reward': typeof RewardRoute
  '/tags': typeof TagsRoute
  '/agents/$config-name': typeof AgentsConfigNameRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/agents/$config-name/general-settings': typeof AgentsConfigNameGeneralSettingsRoute
  '/agents/$config-name/monitor': typeof AgentsConfigNameMonitorRoute
  '/agents/$config-name/': typeof AgentsConfigNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/opc-navigation'
    | '/reward'
    | '/tags'
    | '/agents/$config-name'
    | '/agents'
    | '/agents/$config-name/general-settings'
    | '/agents/$config-name/monitor'
    | '/agents/$config-name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/opc-navigation'
    | '/reward'
    | '/tags'
    | '/agents'
    | '/agents/$config-name/general-settings'
    | '/agents/$config-name/monitor'
    | '/agents/$config-name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/opc-navigation'
    | '/reward'
    | '/tags'
    | '/agents/$config-name'
    | '/agents/'
    | '/agents/$config-name/general-settings'
    | '/agents/$config-name/monitor'
    | '/agents/$config-name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OpcNavigationRoute: typeof OpcNavigationRoute
  RewardRoute: typeof RewardRoute
  TagsRoute: typeof TagsRoute
  AgentsConfigNameRoute: typeof AgentsConfigNameRouteWithChildren
  AgentsIndexRoute: typeof AgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reward': {
      id: '/reward'
      path: '/reward'
      fullPath: '/reward'
      preLoaderRoute: typeof RewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opc-navigation': {
      id: '/opc-navigation'
      path: '/opc-navigation'
      fullPath: '/opc-navigation'
      preLoaderRoute: typeof OpcNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$config-name': {
      id: '/agents/$config-name'
      path: '/agents/$config-name'
      fullPath: '/agents/$config-name'
      preLoaderRoute: typeof AgentsConfigNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$config-name/': {
      id: '/agents/$config-name/'
      path: '/'
      fullPath: '/agents/$config-name/'
      preLoaderRoute: typeof AgentsConfigNameIndexRouteImport
      parentRoute: typeof AgentsConfigNameRoute
    }
    '/agents/$config-name/monitor': {
      id: '/agents/$config-name/monitor'
      path: '/monitor'
      fullPath: '/agents/$config-name/monitor'
      preLoaderRoute: typeof AgentsConfigNameMonitorRouteImport
      parentRoute: typeof AgentsConfigNameRoute
    }
    '/agents/$config-name/general-settings': {
      id: '/agents/$config-name/general-settings'
      path: '/general-settings'
      fullPath: '/agents/$config-name/general-settings'
      preLoaderRoute: typeof AgentsConfigNameGeneralSettingsRouteImport
      parentRoute: typeof AgentsConfigNameRoute
    }
  }
}

interface AgentsConfigNameRouteChildren {
  AgentsConfigNameGeneralSettingsRoute: typeof AgentsConfigNameGeneralSettingsRoute
  AgentsConfigNameMonitorRoute: typeof AgentsConfigNameMonitorRoute
  AgentsConfigNameIndexRoute: typeof AgentsConfigNameIndexRoute
}

const AgentsConfigNameRouteChildren: AgentsConfigNameRouteChildren = {
  AgentsConfigNameGeneralSettingsRoute: AgentsConfigNameGeneralSettingsRoute,
  AgentsConfigNameMonitorRoute: AgentsConfigNameMonitorRoute,
  AgentsConfigNameIndexRoute: AgentsConfigNameIndexRoute,
}

const AgentsConfigNameRouteWithChildren =
  AgentsConfigNameRoute._addFileChildren(AgentsConfigNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OpcNavigationRoute: OpcNavigationRoute,
  RewardRoute: RewardRoute,
  TagsRoute: TagsRoute,
  AgentsConfigNameRoute: AgentsConfigNameRouteWithChildren,
  AgentsIndexRoute: AgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
