/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpcNavigationRouteImport } from './routes/opc-navigation'
import { Route as AgentsOverviewRouteImport } from './routes/agents-overview'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const OpcNavigationRoute = OpcNavigationRouteImport.update({
  id: '/opc-navigation',
  path: '/opc-navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsOverviewRoute = AgentsOverviewRouteImport.update({
  id: '/agents-overview',
  path: '/agents-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents-overview': typeof AgentsOverviewRoute
  '/opc-navigation': typeof OpcNavigationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents-overview': typeof AgentsOverviewRoute
  '/opc-navigation': typeof OpcNavigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents-overview': typeof AgentsOverviewRoute
  '/opc-navigation': typeof OpcNavigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/agents-overview' | '/opc-navigation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/agents-overview' | '/opc-navigation'
  id: '__root__' | '/' | '/about' | '/agents-overview' | '/opc-navigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsOverviewRoute: typeof AgentsOverviewRoute
  OpcNavigationRoute: typeof OpcNavigationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opc-navigation': {
      id: '/opc-navigation'
      path: '/opc-navigation'
      fullPath: '/opc-navigation'
      preLoaderRoute: typeof OpcNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents-overview': {
      id: '/agents-overview'
      path: '/agents-overview'
      fullPath: '/agents-overview'
      preLoaderRoute: typeof AgentsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsOverviewRoute: AgentsOverviewRoute,
  OpcNavigationRoute: OpcNavigationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
