import createFetchClient from "openapi-fetch";
import type { paths } from "../api-schema"; // generated by openapi-typescript

export function getApiFetchClient() {
  let baseUrl = import.meta.env.VITE_API_ORIGIN;
  if (import.meta.env.PROD) {
    baseUrl = window.location.origin;
  }

  return createFetchClient<paths>({
    baseUrl,
  });
}

/**
 * If in development mode, return the API origin from the .env file.
 * If in production mode, return the window location origin, assumes our client is served by the same server as the API.
 * @returns {string} serverOrigin
 */
export const getServerOrigin = () => {
  let serverOrigin = import.meta.env.VITE_API_ORIGIN;
  if (import.meta.env.PROD) {
    serverOrigin = window.location.origin;
  }
  return serverOrigin;
};

/**
 * A utility fetch function with timeout support.
 * @param url - The URL to fetch.
 * @param options - Fetch options (e.g., method, headers, body).
 * @param timeout - Timeout in milliseconds.
 * @returns A promise that resolves with the response or rejects with a timeout error.
 */
export async function fetchWithTimeout(
  url: RequestInfo | URL,
  options: RequestInit = {},
  timeout = 1000, // Default timeout of 1 second
): Promise<Response> {
  // Create a timeout promise that rejects after the specified timeout
  const timeoutPromise = new Promise<never>((_, reject) => {
    setTimeout(() => {
      reject(new Error(`Request timed out after ${timeout}ms`));
    }, timeout);
  });

  // Create the fetch promise
  const fetchPromise = fetch(url, options);

  // Race the fetch promise against the timeout promise
  return Promise.race([fetchPromise, timeoutPromise]);
}
