name: Shared setup workflow

inputs:
  subrepo:
    description: "The subrepo to setup"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - run: |
        cd ${{ inputs.subrepo }}
        uv venv
        uv sync

    - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
