{
 "title": "BESS 2 Objectives",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "BESS 2 Profit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM solar.bess2_metrics WHERE $__timeFilter(\"time\") AND metric LIKE 'RAW-BESS_PROFIT'"
    }
   ]
  },
  {
   "title": "Overall WTP 2/BESS 2/P12 Profit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM solar.bess2_metrics WHERE $__timeFilter(\"time\") AND metric LIKE 'RAW-OVERALL_PROFIT'"
    }
   ]
  },
  {
   "title": "Peak Shaving Setpoint (MW)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_ELSP12_POWER_PEAK_SP_LGC'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Energy Grid Price ($/MWh)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_ENG_IMPORT_COST_SP'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Energy Export Fee ($/MWh)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_ENG_EXPORT_FEE_SP'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Battery Degradation Cost ($/MWh)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_ENG_BATT_COST_SP'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Reward",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'reward'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Reward",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'reward'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Optimization Satisfaction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'optimization_satisfaction'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Optimization Satisfaction",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'optimization_satisfaction'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "BESS 2 Profit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-BESS_PROFIT'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "BESS 2 Profit",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-BESS_PROFIT'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "BESS 2 Costs/Revenue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-CHARGING_FROM_GRID_COST'\nOR metric like 'RAW-CHARGING_FROM_SOLAR_COST'\nOR metric like 'RAW-DISCHARGED_POOL_PRICE_REVENUE'\nOR metric like 'RAW-DISCHARGED_GRID_PRICE_REVENUE'\nOR metric like 'RAW-BESS_DEGRADATION_COST'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "BESS 2 Costs/Revenue",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-CHARGING_FROM_GRID_COST'\nOR metric like 'RAW-CHARGING_FROM_SOLAR_COST'\nOR metric like 'RAW-DISCHARGED_POOL_PRICE_REVENUE'\nOR metric like 'RAW-DISCHARGED_GRID_PRICE_REVENUE'\nOR metric like 'RAW-BESS_DEGRADATION_COST'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "BESS 2 Degradation Profit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-BESS_DEGRADATION_PROFIT'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "BESS 2 Degradation Profit",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-BESS_DEGRADATION_PROFIT'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "WTP 2/BESS 2/P12 Overall Profit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-OVERALL_PROFIT'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "WTP 2/BESS 2/P12 Overall Profit",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-OVERALL_PROFIT'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "P12 Power Peak Constraint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'zones-ELS_SLR_ELSP12_ENG_IN_TOT%'\nAND metric NOT LIKE '%_violation'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Constraint Satisfaction",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric\nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'zones-ELS_SLR_ELSP12_ENG_IN_TOT_violation'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "P12 On-Site Solar Consumption Constraint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'zones-P12_MAJORITY_ON_SITE_CONSUMPTION_CONSTRAINT%'\nAND metric NOT LIKE '%_violation'\nOR metric LIKE 'RAW-ELS_SLR_ELSP12_MAJORITY_LGC'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Constraint Satisfaction",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric\nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'zones-P12_MAJORITY_ON_SITE_CONSUMPTION_CONSTRAINT_violation'\nORDER BY \"time\""
    }
   ]
  }
 ]
}