{
 "title": "BESS 2 Agent Health",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Seconds Since Last Decision",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Time since in seconds\nSELECT EXTRACT(EPOCH FROM (NOW() - MAX(time))) AS seconds_since_last_action\nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'ACTION-%'"
    }
   ]
  },
  {
   "title": "Num Missing Data",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'AE-num_nan_obs'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Num Imputed Data",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'AE-imputed'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Actor PDF - Direct Action Space",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT evaluator, (data->'x')::float as x, (data->'y')::float as y\nFROM solar.bess2_evals, jsonb_array_elements(value->'data') as data\nWHERE $__timeFilter(\"time\") AND agent_step = (\n  SELECT agent_step FROM solar.bess2_evals WHERE $__timeFilter(time) AND evaluator LIKE 'pdf%' ORDER BY time desc LIMIT 1\n)\nAND evaluator LIKE 'pdf%'\nORDER BY \"time\""
    },
    {
     "rawSql": "SELECT value, time, metric \r\nFROM solar.bess2_metrics \r\nWHERE $__timeFilter(\"time\") \r\nAND metric LIKE 'AB-LO-%'\r\nOR metric LIKE 'AB-HI-%'"
    }
   ]
  },
  {
   "title": "Current Action Values",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT evaluator, (data->'x')::float as x, (data->'y')::float as y\nFROM solar.bess2_evals, jsonb_array_elements(value->'data') as data\nWHERE $__timeFilter(\"time\") AND agent_step = (\n  SELECT max(agent_step) FROM solar.bess2_evals WHERE $__timeFilter(time) AND evaluator LIKE 'qs%'\n)\nAND evaluator LIKE 'qs%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "BESS 2 Current SOC + Setpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'ACTION-%'\nOR metric LIKE 'RAW-ELS_SLR_BESS2_SOC'\nOR metric LIKE 'RAW-ELS_SLR_BESS2_SOC_SP_OP'\nOR metric LIKE 'RAW-ELS_SLR_BESS2_SOC_SP_AI'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "AI Mode (1) / Operator Mode (0)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_BESS2_CTRL_MODE'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Agent Uncertainty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'q_ensemble_var'\n-- OR metric LIKE 'CRITIC%_q'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Prediction Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'partial_return'\nOR metric LIKE 'observed_a_q'\nORDER BY \"time\""
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 }, "options": { "content": "# Data Health\n" } },
  {
   "title": "Pool Price",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-Actual_Posted_Pool_Price'\nOR metric like 'RAW-Forecast_Pool_Price%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-Actual_Posted_Pool_Price%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Charging Source/Discharging Destination",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-CHARGING_FROM_GRID'\nOR metric like 'RAW-CHARGING_FROM_SOLAR'\nOR metric like 'RAW-ALL_ENERGY_DISCHARGED_POOL_PRICE'\nOR metric like 'RAW-ALL_ENERGY_DISCHARGED_GRID_PRICE'\nOR metric like 'RAW-SOME_ENERGY_DISCHARGED_POOL_PRICE'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "BESS Costs/Revenue",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-CHARGING_FROM_GRID_COST'\nOR metric like 'RAW-CHARGING_FROM_SOLAR_COST'\nOR metric like 'RAW-DISCHARGED_POOL_PRICE_REVENUE'\nOR metric like 'RAW-DISCHARGED_GRID_PRICE_REVENUE'\nOR metric like 'RAW-BESS_DEGRADATION_COST'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-BESS_DEGRADATION_COST%'\nOR metric LIKE 'STATE-QUALITY-CHARGING_FROM_GRID_COST%'\nOR metric LIKE 'STATE-QUALITY-CHARGING_FROM_SOLAR_COST%'\nOR metric LIKE 'STATE-QUALITY-DISCHARGED_POOL_PRICE_REVENUE%'\nOR metric LIKE 'STATE-QUALITY-DISCHARGED_GRID_PRICE_REVENUE%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_BESS2_ENG_IN_TOT'\nOR metric like 'RAW-ELS_SLR_BESS2_ENG_OUT_TOT'\nOR metric like 'RAW-ELS_SLR_WTP2_ENG_IN_TOT'\nOR metric like 'RAW-ELS_SLR_SOLAR2_ENG_OUT_TOT'\nOR metric like 'RAW-ELS_SLR_ELSP12_ENG_IN_TOT'\nOR metric like 'RAW-ELS_SLR_ELSP12_ENG_OUT_TOT'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-ELS_SLR_BESS2_ENG_IN_TOT%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_BESS2_ENG_OUT_TOT%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_WTP2_ENG_IN_TOT%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_SOLAR2_ENG_OUT_TOT%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_ELSP12_ENG_IN_TOT%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_ELSP12_ENG_OUT_TOT%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_BESS2_KW'\nOR metric like 'RAW-ELS_SLR_WTP2_KW'\nOR metric like 'RAW-ELS_SLR_SOLAR2_KW'\nOR metric like 'RAW-ELS_SLR_ELSP12_KW'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-ELS_SLR_BESS2_KW%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_WTP2_KW%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_SOLAR2_KW%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_ELSP12_KW%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Reactive Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 91 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_BESS2_KVAR'\nOR metric like 'RAW-ELS_SLR_WTP2_KVAR'\nOR metric like 'RAW-ELS_SLR_SOLAR2_KVAR'\nOR metric like 'RAW-ELS_SLR_ELSP12_KVAR'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-ELS_SLR_BESS2_KVAR%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_WTP2_KVAR%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_SOLAR2_KVAR%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_ELSP12_KVAR%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "BESS 1A/B Availability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 101 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_PS1000_2A_AVAIL'\nOR metric like 'RAW-ELS_SLR_PS1000_2B_AVAIL'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-ELS_SLR_PS1000_2A_AVAIL%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_PS1000_2B_AVAIL%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "SOLAR 1 Inverter Availability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 111 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_INV2_AVAIL'\nOR metric like 'RAW-ELS_SLR_INV4_AVAIL'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-ELS_SLR_INV2_AVAIL%'\nOR metric LIKE 'STATE-QUALITY-ELS_SLR_INV4_AVAIL%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "SOLAR 1 Inverter Limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 121 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SLR_SOLAR2_LIMIT_LGC'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 121 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-ELS_SLR_SOLAR2_LIMIT_LGC%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 131 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SITE_MET_BOP_TEMP'\nOR metric LIKE 'RAW-ELS_SITE_MET_OUT_TEMP'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-ELS_SITE_MET_BOP_TEMP%'\nOR metric LIKE 'STATE-QUALITY-ELS_SITE_MET_OUT_TEMP%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Solar Irradiance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 141 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-ELS_SITE_MET_POA'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 141 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-ELS_SITE_MET_POA%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Alberta Internal Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 151 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'RAW-Current_AIL'\nOR metric LIKE 'RAW-Forecast_AIL_1'\nOR metric LIKE 'RAW-Forecast_AIL_2'\nOR metric LIKE 'RAW-Forecast_AIL_3'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "State Quality",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 151 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'STATE-QUALITY-Current_AIL%'\nOR metric LIKE 'STATE-QUALITY-Forecast_AIL_%'\nORDER BY \"time\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 161 },
   "options": {
    "content": "# Agent Neural Network Health\n"
   }
  },
  {
   "title": "Critic Losses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE 'CRITIC0_loss'\nOR metric LIKE 'CRITIC1_loss'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Network Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "targets": [
    {
     "rawSql": "SELECT value, time, metric \nFROM solar.bess2_metrics \nWHERE $__timeFilter(\"time\") \nAND metric LIKE '%stable_rank%'\nORDER BY \"time\""
    }
   ]
  }
 ]
}