log_path: outputs/main/backwash
agent_name: main_backwash
seed: 1
is_simulation: false
feature_flags:
  nominal_setpoint_bias: true
  normalize_return: true
  autoencoder_imputer: false
infra:
  db:
    drivername: postgresql+psycopg2
    username: postgres
    password: password
    ip: localhost
    port: 5432
    db_name: postgres
agent:
  name: greedy_ac
  gamma: 0.9928
interaction:
  name: dep_interaction
  restore_checkpoint: false
  checkpoint_path: outputs/checkpoints/main
  obs_period: 00:15:00
  update_period: 00:01:00
  action_period: 04:00:00
  warmup_period: 259200
  update_warmup: 30
  historical_batch_size: 8640
  historical_windows:
  - 2025-01-01 00:00:00+0000
  - null
event_bus:
  enabled: true
  cli_connection: tcp://localhost:5561
coreio:
  coreio_origin: tcp://localhost:5560
  opc_connections:
  - connection_id: main_opc
    opc_conn_url: opc.tcp://localhost:50505
    application_uri: main_bw
    security_policy:
      policy: none
      mode: none
    authentication_mode: anonymous
env:
  name: dep_async_env
  db:
    table_name: main
metrics:
  enabled: true
  table_name: metrics_main_bw
evals:
  enabled: true
  table_name: evals_main_bw
pipeline:
  reward:
    priorities:
    - op: down_to
      tag: BP_CYCLE_TOTAL
      thresh: 3500
    - tags:
      - PERMEABILITY
      directions: max
      weights:
      - 1.0
  state_constructor:
    defaults:
    - name: multi_trace
      trace_values:
      - 0.0
      - 0.97
  trajectory_creator:
    name: all-the-time
    min_n_step: 15
    max_n_step: 16
  trajectory_filter:
    filters:
    - only_pre_dp_or_ac
    - only_post_dp
    - no_nan
    - only_no_action_change
  tags:
  - name: DEP_BP_FLOW_SP_WA
    connection_id: main_opc
    node_identifier: ns=1;s=ai_flow_sp
    operating_range:
    - 120
    - 179
    type: ai_setpoint
    agg: last
  - name: DEP_BP_DUR_SP_WA
    connection_id: main_opc
    node_identifier: ns=1;s=ai_dur_sp
    operating_range:
    - 10
    - 30
    type: ai_setpoint
    agg: last
  - name: PERMEABILITY
    operating_range:
    - 0
    - 10
    expected_range:
    - 5
    - 7
    is_computed: true
    value: -{UF2_FIT301_PV}/{UF2_TMP_PV}
    outlier:
    - name: exp_moving
      alpha: 0.9928
    imputer:
      name: copy
      imputation_horizon: 96
    filter:
    - name: comparator
      op: '>'
      val: 100000
    - name: binary
      op: max
      other: UF2_SEQ_STATE
      other_xform:
      - name: comparator
        op: '!='
        val: 8
    - name: binary
      op: max
      other: UF2_FIT301_PV
      other_xform:
      - name: comparator
        op: <
        val: 10
    - name: binary
      op: max
      other: UF2_TMP_PV
      other_xform:
      - name: comparator
        op: '>'
        val: -1
  - name: UF2_FIT301_PV
    preprocess:
    - name: identity
    state_constructor:
    - name: nuke
  - name: UF2_TMP_PV
    state_constructor:
    - name: nuke
  - name: UF2_SEQ_STATE
    operating_range:
    - 1
    - 2048
    state_constructor:
    - name: nuke
  - name: BP_CYCLE_TOTAL
    operating_range:
    - 0
    - 5500
    expected_range:
    - 1300
    - 5000
  - name: UV01_UV254_PV
    operating_range:
    - 0
    - 110
  - name: UV03_UV254_PV
    operating_range:
    - 0
    - 110
  - name: FLR01_TRYP_PV
    operating_range:
    - 0
    - 10
  - name: FLR03_TRYP_PV
    operating_range:
    - 0
    - 10
    expected_range:
    - 2
    - 7
  - name: FLR04_TRYP_PV
    operating_range:
    - 0
    - 20
  - name: FLR01_CDOM_PV
    operating_range:
    - 0
    - 100
  - name: FLR03_CDOM_PV
    operating_range:
    - 0
    - 100
    expected_range:
    - 15
    - 40
  - name: AIT310_PV
    expected_range:
    - 0
    - 150
    operating_range:
    - 0
    - null
  - name: AIT320_PV
    operating_range:
    - 0
    - 30
  - name: AIT_130_PV
    operating_range:
    - 6.5
    - 8.5
  - name: IM_A_TAG0
    connection_id: main_opc
    node_identifier: ns=1;s=ai_flow_sp
    operating_range:
    - 10
    - 79
  - additionalProp1: {}
  - additionalProp1: {}
  - additionalProp1: {}
  - additionalProp1: {}
  - additionalProp1: {}
  - additionalProp1: {}
