log_path: outputs/main/backwash
agent_name: Test_Config
seed: 1
is_simulation: False

feature_flags:
  nominal_setpoint_bias: true
  normalize_return: true
  autoencoder_imputer: false

infra:
  db:
    drivername: "postgresql+psycopg2"
    username: "postgres"
    password: "password"
    ip: "localhost"
    port: 5432
    db_name: "postgres"

agent:
  name: greedy_ac
  gamma: 0.9928 # half life 24h

interaction:
  name: dep_interaction
  restore_checkpoint: False
  checkpoint_path: 'outputs/checkpoints/main'
  obs_period: 00:15:00 # prod lasts ~45 minutes
  update_period: 00:01:00
  action_period: 04:00:00 # backwash every ~4.5 hours
  warmup_period: 72:00:00
  update_warmup: 30 # number of updates before interacting
  historical_batch_size: 8640 # 90 days @ 15 minute obs period
  historical_windows:
  - [2025-01-01 00:00:00+0000, null]

event_bus:
  enabled: True
  cli_connection: tcp://localhost:5561

coreio:
  coreio_origin: "tcp://localhost:5560"
  opc_connections:
    - connection_id: main_opc
      opc_conn_url: "opc.tcp://localhost:50505"
      application_uri: main_bw
      security_policy:
        policy: none
        mode: none
      authentication_mode: anonymous


env:
  name: dep_async_env
  db:
    table_name: "main"

metrics:
  enabled: True
  table_name: metrics_main_bw

evals:
  enabled: True
  table_name: evals_main_bw

pipeline:
  reward:
    priorities:
    - op: down_to
      tag: BP_CYCLE_TOTAL
      thresh: 3500
    - tags:
      - PERMEABILITY
      directions: max
      weights:
      - 1.0

  state_constructor:
    defaults:
      - name: multi_trace
        trace_values: [0., 0.97] # half life 2 hours

  transition_creator:
    name: all-the-time
    # n_step should be 16, give some buffer
    min_n_step: 15
    max_n_step: 16

  transition_filter:
    filters:
    - "only_pre_dp_or_ac"
    - "only_post_dp"
    - "no_nan"
    - "only_no_action_change"

  tags:
  - name: DEP_BP_FLOW_SP_WA
    connection_id: main_opc
    node_identifier: "ns=1;s=ai_flow_sp"
    operating_range: [120, 179]
    type: ai_setpoint
    agg: last

  
