SWEEP_PARAMS = {
    'agent': ['greedy_ac'],
    'env': ['delayed_saturation'],
    'data_loader' : ['direct_action'],
    'interaction' : ['anytime'],
    'state_constructor' : ['anytime_multi_trace'],
    'experiment.device': ["cuda:0"],
    'experiment.exp_name': ["Double_Reduct_Delayed_Saturation_Prefilled_Buffer"],
    'experiment.max_steps': [10000],
    'experiment.offline_steps': [1],
    'experiment.gamma': [0.95, 0.99],
    'agent.tau': [0.0],
    'agent.rho': [0.04],
    'agent.prop_rho_mult': [2.0],
    'agent.num_samples': [256],
    'agent.uniform_proposal': [True],
    'agent.critic.polyak': [0.995],
    'agent.critic.critic_network.ensemble': [10],
    'agent.critic.critic_network.bootstrap_reduct': ["min", "median", "mean", "max"],
    'agent.critic.critic_network.policy_reduct': ["min", "median", "mean", "max"],
    'agent.critic.critic_network.vmap': [False],
    'agent.critic.critic_optimizer.lr': [0.0003],
    'agent.critic.critic_optimizer.weight_decay': [0.0, 0.01],
    'agent.critic.buffer.batch_size': [512],
    'agent.critic.buffer.data_subset': [0.9],
    'agent.actor.actor_optimizer.lr': [0.001],
    'agent.actor.actor_network.tanh_shift': [-4.0],
    'agent.actor.buffer.batch_size': [128],
}