SWEEP_PARAMS = {
    'agent': ['greedy_ac'],
    'env': ['delayed_saturation'],
    'data_loader' : ['direct_action'],
    'interaction' : ['anytime'],
    'state_constructor' : ['anytime_multi_trace'],
    'experiment.device': ["cpu"],
    'experiment.exp_name': ["Merge_Debug_LR_Sweep"],
    'experiment.max_steps': [10000],
    'experiment.offline_steps': [5000],
    'experiment.gamma': [0.99],
    'experiment.online_updates': [True],
    'agent.tau': [0.0],
    'agent.rho': [0.04],
    'agent.prop_rho_mult': [2.0],
    'agent.num_samples': [256],
    'agent.uniform_proposal': [True],
    'agent.n_critic_updates': [1, 5],
    'agent.n_actor_updates': [1],
    'agent.critic.polyak': [0.995],
    'agent.critic.critic_network.ensemble': [10],
    'agent.critic.critic_network.bootstrap_reduct': ["min", "mean"],
    'agent.critic.critic_network.policy_reduct': ["min", "mean"],
    'agent.critic.critic_network.vmap': [False],
    'agent.critic.critic_optimizer.lr': [0.0001, 0.001],
    'agent.critic.critic_optimizer.weight_decay': [0.0],
    'agent.critic.buffer.batch_size': [512],
    'agent.critic.buffer.data_subset': [0.8],
    'agent.actor.actor_optimizer.lr': [0.0001, 0.001],
    'agent.actor.actor_network.tanh_shift': [-4.0],
    'agent.actor.buffer.batch_size': [128],
}